DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'belek_reward_system') THEN
        CREATE SCHEMA belek_reward_system;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS belek_reward_system."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'belek_reward_system') THEN
            CREATE SCHEMA belek_reward_system;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.users (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        full_name text NOT NULL,
        username text NOT NULL,
        password_hash text NOT NULL,
        role text NOT NULL,
        email text,
        department text,
        grade text,
        created_at timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.articles (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        title text NOT NULL,
        journal text,
        doi text,
        year integer,
        score integer,
        status text,
        created_at timestamp without time zone NOT NULL,
        "FilePath" text,
        CONSTRAINT "PK_articles" PRIMARY KEY (id),
        CONSTRAINT "FK_articles_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.badges (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        badge_name text NOT NULL,
        description text,
        icon text,
        color text,
        earned_at timestamp without time zone NOT NULL,
        CONSTRAINT "PK_badges" PRIMARY KEY (id),
        CONSTRAINT "FK_badges_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.competitions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        description text,
        organization text,
        category text,
        start_at timestamp without time zone,
        end_at timestamp without time zone,
        status text,
        gives_certificate boolean NOT NULL,
        reward_details text,
        created_by bigint,
        approved_by_manager boolean NOT NULL,
        approved_at timestamp without time zone,
        CONSTRAINT "PK_competitions" PRIMARY KEY (id),
        CONSTRAINT "FK_competitions_users_created_by" FOREIGN KEY (created_by) REFERENCES belek_reward_system.users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.notes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        content text NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT "PK_notes" PRIMARY KEY (id),
        CONSTRAINT "FK_notes_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.notifications (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        message text NOT NULL,
        is_read boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT "PK_notifications" PRIMARY KEY (id),
        CONSTRAINT "FK_notifications_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.patents (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        title text NOT NULL,
        patent_number text,
        year integer,
        status text,
        created_at timestamp without time zone NOT NULL,
        "FilePath" text,
        CONSTRAINT "PK_patents" PRIMARY KEY (id),
        CONSTRAINT "FK_patents_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.presentations (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        title text NOT NULL,
        conference text,
        year integer,
        status text,
        created_at timestamp without time zone NOT NULL,
        "FilePath" text,
        CONSTRAINT "PK_presentations" PRIMARY KEY (id),
        CONSTRAINT "FK_presentations_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.projects (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        title text NOT NULL,
        description text,
        start_date timestamp without time zone,
        end_date timestamp without time zone,
        status text,
        created_at timestamp without time zone NOT NULL,
        "FilePath" text,
        CONSTRAINT "PK_projects" PRIMARY KEY (id),
        CONSTRAINT "FK_projects_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.article_teacher_assignments (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        article_id bigint NOT NULL,
        teacher_id bigint NOT NULL,
        weight_percentage integer NOT NULL,
        given_score integer NOT NULL,
        is_completed boolean NOT NULL,
        CONSTRAINT "PK_article_teacher_assignments" PRIMARY KEY (id),
        CONSTRAINT "FK_article_teacher_assignments_articles_article_id" FOREIGN KEY (article_id) REFERENCES belek_reward_system.articles (id) ON DELETE CASCADE,
        CONSTRAINT "FK_article_teacher_assignments_users_teacher_id" FOREIGN KEY (teacher_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.certificates (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        competition_id bigint NOT NULL,
        certificate_name text NOT NULL,
        ranking integer,
        issued_at timestamp without time zone NOT NULL,
        approved_by_manager boolean NOT NULL,
        approved_at timestamp without time zone,
        CONSTRAINT "PK_certificates" PRIMARY KEY (id),
        CONSTRAINT "FK_certificates_competitions_competition_id" FOREIGN KEY (competition_id) REFERENCES belek_reward_system.competitions (id) ON DELETE CASCADE,
        CONSTRAINT "FK_certificates_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE TABLE belek_reward_system.competition_applications (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        competition_id bigint NOT NULL,
        applied_at timestamp without time zone NOT NULL,
        status text,
        ranking integer,
        CONSTRAINT "PK_competition_applications" PRIMARY KEY (id),
        CONSTRAINT "FK_competition_applications_competitions_competition_id" FOREIGN KEY (competition_id) REFERENCES belek_reward_system.competitions (id) ON DELETE CASCADE,
        CONSTRAINT "FK_competition_applications_users_user_id" FOREIGN KEY (user_id) REFERENCES belek_reward_system.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_article_teacher_assignments_article_id" ON belek_reward_system.article_teacher_assignments (article_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_article_teacher_assignments_teacher_id" ON belek_reward_system.article_teacher_assignments (teacher_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_articles_user_id" ON belek_reward_system.articles (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_badges_user_id" ON belek_reward_system.badges (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_certificates_competition_id" ON belek_reward_system.certificates (competition_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_certificates_user_id" ON belek_reward_system.certificates (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_competition_applications_competition_id" ON belek_reward_system.competition_applications (competition_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_competition_applications_user_id" ON belek_reward_system.competition_applications (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_competitions_created_by" ON belek_reward_system.competitions (created_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_notes_user_id" ON belek_reward_system.notes (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_notifications_user_id" ON belek_reward_system.notifications (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_patents_user_id" ON belek_reward_system.patents (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_presentations_user_id" ON belek_reward_system.presentations (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    CREATE INDEX "IX_projects_user_id" ON belek_reward_system.projects (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM belek_reward_system."__EFMigrationsHistory" WHERE "MigrationId" = '20260501124247_AddFilePathToAcademics') THEN
    INSERT INTO belek_reward_system."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260501124247_AddFilePathToAcademics', '8.0.0');
    END IF;
END $EF$;
COMMIT;

